version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
  web:
    build: ./project
    command: 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - './project:/app'
      - './public:/app/public'
    environment:
      PGDATA: /tmp
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - db
    env_file:
      - dev.env
  unicorn:
    build: ./project
    command: /bin/bash /app/start.sh
    volumes:
      - './project:/app'
      - './public:/app/public'
    ports:
      - '5000:5000'
      - '587:587'
    restart: always
    depends_on:
      - db
    env_file:
      - dev.env
      - dev-wsgi.env
